# Artificial Neural Network

### Importing the libraries

In [7]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [8]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [9]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [10]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

## Part 2 - Building the ANN

### Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [20]:
ann.compile(optimizer="adam", loss="mean_squared_error")

### Training the ANN model on the Training set

In [21]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
225/225 [==============================] - 1s 2ms/step - loss: 34965.6133
Epoch 2/100
225/225 [==============================] - 0s 2ms/step - loss: 323.4329
Epoch 3/100
225/225 [==============================] - 0s 2ms/step - loss: 310.5876
Epoch 4/100
225/225 [==============================] - 0s 2ms/step - loss: 294.8719
Epoch 5/100
225/225 [==============================] - 0s 2ms/step - loss: 276.1291
Epoch 6/100
225/225 [==============================] - 0s 2ms/step - loss: 256.5000
Epoch 7/100
225/225 [==============================] - 0s 2ms/step - loss: 235.5601
Epoch 8/100
225/225 [==============================] - 1s 3ms/step - loss: 213.1134
Epoch 9/100
225/225 [==============================] - 1s 3ms/step - loss: 191.1324
Epoch 10/100
225/225 [==============================] - 1s 3ms/step - loss: 169.1922
Epoch 11/100
225/225 [==============================] - 0s 2ms/step - loss: 148.3351
Epoch 12/100
225/225 [==============================] - 0s 2ms/step - lo